/**
 * Deterministic fuzzy matching for the voice grammar — a post-processing
 * safety net over the vosk grammar: a misheard word ("heeding" for
 * "heading") must still resolve.
 *
 * Rules (locked 2026-08-05, exhaustive acceptance table generated by
 * scripts/gen_voice_fuzzy_acceptance.mjs — see the deviation matrix for the
 * end-to-end rows):
 *   - Exact matches ALWAYS win (fuzzy never fires on an exact token).
 *   - Tokens shorter than 3 chars are exact-only, EXCEPT the 'to' carve-out
 *     (SAPI renders "two zero zero" as "to zero zero" constantly — 'to'
 *     maps to 'two' in the number slot and receives 'two'/'too' in the
 *     pattern slot).
 *   - NON_FUZZY_WORDS (fillers) never fuzzy-map in ANY slot — 'uh' must not
 *     become 'oh' → 0, 'sir' must not become 'air', 'um' must not become 'm'.
 *     (Their exact forms still match — "okay airways" is an airline.)
 *   - CURATED_EXCLUDE blocks semantic inversions that D-L distance would
 *     otherwise accept: 'ascend' → 'descend' (climb becomes descent) and
 *     'decrease' → 'increase' (deceleration becomes acceleration) — both
 *     within distance 2 of their antonym.
 *   - CURATED_CONFUSABLES covers multi-token spelled-out forms D-L can't
 *     catch ("eye el ess" → ils, "eff el" → fl).
 *   - Everything deterministic: array order, strictly-lower distance wins,
 *     ties first-wins, no randomness.
 *   - 2026-08-06 amendment: enSkeleton() consonant-skeleton stage for the
 *     closed-set fallback slots (airline name words, runway-number spoken
 *     forms) — deterministic, digraph-mapped (th→θ, ch→x, silent gh
 *     dropped), guards: first symbol equal, min skeleton 2, raw-length
 *     diff ≤ 2, skeleton D-L exactly 1, unique best wins / ties fail; the
 *     flight-number fuzzy guard is unchanged.
 *
 * Pure + DOM-free, imports nothing (leaf module — it is imported by
 * voiceNumberParser, voiceCallsignParser and voiceTranscriptParser).
 */

// ─── Damerau-Levenshtein (optimal string alignment) ────────────────────

/** Restricted edit distance: insert/delete/substitute + adjacent transposition = 1. */
export function damerauLevenshtein(a, b) {
  const n = a.length;
  const m = b.length;
  const d = new Array(n + 1);
  for (let i = 0; i <= n; i++) {
    d[i] = new Array(m + 1);
    d[i][0] = i;
  }
  for (let j = 0; j <= m; j++) d[0][j] = j;
  for (let i = 1; i <= n; i++) {
    for (let j = 1; j <= m; j++) {
      let c = d[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1);
      if (i > 1 && j > 1 && a[i - 1] === b[j - 2] && a[i - 2] === b[j - 1]) {
        c = Math.min(c, d[i - 2][j - 2] + 1); // adjacent transposition
      }
      d[i][j] = Math.min(c, d[i - 1][j] + 1, d[i][j - 1] + 1);
    }
  }
  return d[n][m];
}

// ─── Thresholds & eligibility ──────────────────────────────────────────

/** Distance cap for pattern/airline words: ≤5 chars → 1, ≥6 → 2. */
export function maxDistForWord(word) {
  return word.length <= 5 ? 1 : 2;
}

/** Tokens below this length are exact-only (except SHORT_FUZZY_TOKENS). */
export const MIN_FUZZY_LEN = 3;

/** 2-char tokens allowed the fuzzy path — real SAPI artifacts that
 *  drop/alter the trailing consonant of a grammar word:
 *    "to" → two (the big one — SAPI renders "two zero zero" as "to zero zero"),
 *    "an" → and ("one hundred an fifty"),
 *    "on" → one ("on zero zero"),
 *    "of" → off ("level of 9000").
 *  Each maps to exactly one grammar word at distance 1 (verified against the
 *  acceptance generator); everything else under MIN_FUZZY_LEN stays exact-only
 *  ("ho" must never become "oh"). */
export const SHORT_FUZZY_TOKENS = ['to', 'an', 'on', 'of'];

/** Whether a recognized token may take the fuzzy path. */
export function isFuzzyEligible(token) {
  return token.length >= MIN_FUZZY_LEN || SHORT_FUZZY_TOKENS.includes(token);
}

// ─── Flight-number fuzzy guard ─────────────────────────────────────────

/** Command words that must never be fuzzy-mapped inside a FLIGHT NUMBER.
 *  "CSC6918: right heading 120" — 'right' is distance 1 from 'eight', so
 *  without this guard the number scan swallows the command word and the
 *  callsign becomes CSC69188 (wrong aircraft = worst failure mode).
 *  Exact number-word lookups are unaffected; the guard only blocks the
 *  fuzzy fallback. Pinned to the pattern table by
 *  voiceFuzzyAcceptance.test.js (no drift allowed). */
export const FLIGHT_NUMBER_FUZZY_GUARD = new Set([
  'turn', 'left', 'right', 'to', 'heading', 'climb', 'and', 'maintain',
  'descend', 'level', 'off', 'at', 'reduce', 'speed', 'increase', 'slow',
  'down', 'fly', 'altitude', 'flight', 'fl', 'direct',
]);

// ─── Never-fuzzy words (fillers) ───────────────────────────────────────

/** Fillers are stripped/ignored elsewhere; they must never fuzzy-map.
 *  Single source — voiceCallsignParser re-exports these as EN_FILLER_WORDS. */
export const NON_FUZZY_WORDS = ['uh', 'um', 'er', 'ah', 'okay', 'ok', 'sir', 'please'];

const NON_FUZZY_SET = new Set(NON_FUZZY_WORDS);

// ─── Semantic-inversion blacklist ──────────────────────────────────────

/** Recognized tokens that must never map to these grammar words even when
 *  the D-L distance fits (a climb must never become a descent, an increase
 *  must never become a decrease). */
export const CURATED_EXCLUDE = {
  descend: ['ascend'],
  increase: ['decrease'],
};

// ─── Curated multi-token confusables ───────────────────────────────────

/** Multi-token spelled-out forms D-L can't catch. Keys are grammar tokens,
 *  values are the joined-phrase forms a dictation engine emits for them.
 *  All keys have a spoken-letter form a pilot might say; 'direct' is the one
 *  pure-mishearing entry ("the wreck" for /dəˈrekt/, two tokens — D-L ≥ 3
 *  from every single pattern word, so the fuzzy path can never catch it). */
export const CURATED_CONFUSABLES = {
  ils: ['eye el ess', 'i l s', 'ai el ess', 'eye ell ess'],
  rnav: ['r nav', 'ar nav', 'r navv', 'ar navv'],
  loc: ['el o cee', 'l o c'],
  vor: ['vee or', 'v or', 'vee oh ar'],
  ndb: ['en dee bee', 'en dee b', 'n d b'],
  direct: ['the wreck'],
  fl: ['eff el', 'eff ell', 'eff e l'],
};

/** Reverse-lookup a joined token phrase against the curated table.
 *  @param {string} joined — tokens joined with ' ' ("eye el ess")
 *  @param {string} [target] — restrict to one canonical token ("ils")
 *  @returns {string|null} canonical token, or null */
export function resolveCuratedPhrase(joined, target) {
  for (const [canonical, variants] of Object.entries(CURATED_CONFUSABLES)) {
    if (target && canonical !== target) continue;
    if (variants.includes(joined)) return canonical;
  }
  return null;
}

// ─── Spelled-letter table (waypoint slot) ───────────────────────────────

/** Spoken forms per letter. First form = the CANONICAL grammar word (ICAO
 *  spelling alphabet — the vosk decoder must hear it); second form = the
 *  common letter name (also grammar words — scripts/gen-vosk-grammar.mjs
 *  takes forms.slice(0, 2), exactly 26 + 26 = 52 words). Any further forms
 *  below ('el', 'see', 'zed', bare letters, …) are PARSER-ONLY tolerance
 *  (typed/CLI) — never grammar words (1-char tokens would pollute the
 *  decoder, and 'el'/'see' are risky additions to a constrained vocab).
 *  Small-model OOV (scripts/check-vosk-vocab.mjs): aitch/juliett/xray are
 *  skipped by the decoder — every letter still has an in-vocab form
 *  (H→hotel, J→jay, X→ex), so spoken spelling works; the OOV forms remain
 *  typed/CLI tolerance. */
export const EN_LETTER_WORDS = {
  a: ['alpha', 'ay'],            b: ['bravo', 'bee'],
  c: ['charlie', 'cee', 'see'],  d: ['delta', 'dee'],
  e: ['echo', 'ee'],             f: ['foxtrot', 'eff'],
  g: ['golf', 'gee'],            h: ['hotel', 'aitch', 'haitch'],
  i: ['india', 'eye'],           j: ['juliett', 'jay', 'juliet'],
  k: ['kilo', 'kay'],            l: ['lima', 'ell', 'el'],
  m: ['mike', 'em'],             n: ['november', 'en'],
  o: ['oscar', 'oh'],            p: ['papa', 'pee'],
  q: ['quebec', 'cue'],          r: ['romeo', 'ar', 'are'],
  s: ['sierra', 'ess'],          t: ['tango', 'tee'],
  u: ['uniform', 'you'],         v: ['victor', 'vee'],
  w: ['whiskey', 'dubya'],       x: ['xray', 'ex'],
  y: ['yankee', 'why'],          z: ['zulu', 'zee', 'zed'],
};

/** Reverse map: spoken form (lowercase) → letter, incl. parser-only
 *  variants and bare single letters ("b" → B — typed input only). */
export const LETTER_WORD_TO_LETTER = (() => {
  const m = new Map();
  for (const [letter, forms] of Object.entries(EN_LETTER_WORDS)) {
    for (const f of forms) m.set(f, letter);
    m.set(letter, letter);
  }
  return m;
})();

/** Multi-token letter forms ("double you" = W) — consumed as ONE letter. */
export const TWO_TOKEN_LETTERS = new Map([
  ['double u', 'w'], ['double you', 'w'], ['x ray', 'x'],
]);

// ─── Phonetic consonant-skeleton fallback (2026-08-06) ─────────────────

/**
 * Deterministic consonant skeleton (metaphone-style) for the closed-set
 * fallback slots (airline name words, runway-number spoken forms).
 * Pipeline: lowercase → drop non-letters → collapse silent 'gh'
 * ('eight'→t) → map 'th'→θ ('cathay'→cθ) → map 'ch'→x ('china'→xn —
 * keeps c-initial words from collapsing onto it) → drop vowels aeiou and
 * glides y/h/w. One symbol per consonant sound, so skeleton D-L 1 means
 * one misheard consonant — the exact envelope of a dictation engine's
 * sound confusions ('cafe'↔'cathay' cf/cθ, 'ethiopian'↔'three one'
 * θpn/θrn).
 */
export function enSkeleton(word) {
  return word.toLowerCase()
    .replace(/[^a-z]/g, '')
    .replace(/gh/g, '')
    .replace(/th/g, 'θ')
    .replace(/ch/g, 'x')
    .replace(/[aeiouyh]/g, '');
}

/**
 * Closed-set phonetic fallback match: match a token against candidate
 * words by consonant skeleton (enSkeleton). Rules:
 *   - both skeletons non-empty with min length ≥ 2 (1-symbol forms like
 *     'one'/'two'/'air' stay exact/D-L-only, never phonetic),
 *   - first skeleton symbol equal ('banana' b never reaches a runway form),
 *   - raw-length diff ≤ 2 ('cafe' 4 vs 'cathay' 6 — blocks 3-char OOV
 *     tokens from reaching 5-char words),
 *   - skeleton D-L EXACTLY 1 — a D-L-0 pair ('ghost'/'asset' → 'st') must
 *     not resolve; the raw D-L layer already covers near-identical words.
 * Unique best wins, ties fail (deterministic — mirrors the waypoint tie
 * rule). Candidates must be a CLOSED SET (airline name words, runway
 * spoken forms) — random vocabulary stays rejected.
 *
 * @param {string} token — recognized word (lowercase)
 * @param {string[]} candidates — closed-set words to match against
 * @returns {string|null} the unique best candidate, or null
 */
export function skeletonMatch(token, candidates) {
  const skel = enSkeleton(token);
  if (!skel || skel.length < 2) return null;
  let best = null;
  let count = 0;
  for (const c of candidates) {
    const cskel = enSkeleton(c);
    if (!cskel || cskel.length < 2) continue;
    if (cskel[0] !== skel[0]) continue;
    if (Math.abs(c.length - token.length) > 2) continue;
    if (damerauLevenshtein(skel, cskel) === 1) { best = c; count++; }
  }
  return count === 1 ? best : null;
}

// ─── Match helpers ─────────────────────────────────────────────────────

/**
 * Best candidate within distance cap of token, or null.
 * Exact-first (returns {candidate: token, dist: 0} on exact hit, even for
 * fillers like "okay airways"), then NON_FUZZY block, then D-L search with
 * CURATED_EXCLUDE. Deterministic: array order, strictly-lower distance wins,
 * ties first-wins.
 *
 * The cap may be a single number OR a per-candidate function — the pattern
 * slot's cap is a property of the candidate word (≤5 chars → 1, ≥6 → 2),
 * so a search over mixed-length candidates must cap per candidate.
 *
 * @param {string} token — recognized word (lowercase)
 * @param {string[]} candidates — grammar words to match against (lowercase)
 * @param {number|((candidate: string) => number)} [cap] — default maxDistForWord
 * @returns {{candidate: string, dist: number} | null}
 */
export function fuzzyMatch(token, candidates, cap = maxDistForWord) {
  if (!isFuzzyEligible(token)) return null;
  const capFn = typeof cap === 'function' ? cap : () => cap;

  // Exact-first — also lets filler-token airline names ("okay airways")
  // keep matching exactly.
  for (const c of candidates) {
    if (c === token) return { candidate: token, dist: 0 };
  }

  if (NON_FUZZY_SET.has(token)) return null;

  let best = null;
  for (const c of candidates) {
    const excluded = CURATED_EXCLUDE[c] && CURATED_EXCLUDE[c].includes(token);
    if (excluded) continue;
    const capC = capFn(c);
    if (Math.abs(c.length - token.length) > capC) continue;
    const dist = damerauLevenshtein(token, c);
    if (dist > 0 && dist <= capC && (!best || dist < best.dist)) {
      best = { candidate: c, dist };
    }
  }
  return best;
}

/**
 * Table-site variant: return the matching KEY string (for lookups into
 * EN_DIGIT / EN_TEEN / EN_TENS / EN_UNIT_WORDS / pattern word lists).
 *
 * @param {string} token — recognized word (lowercase)
 * @param {string[]} keys — table keys, in table order (order breaks ties)
 * @param {number} [maxDist] — pass explicitly for numbers/units (flat ≤ 1)
 * @returns {string|null} the matched key
 */
export function fuzzyLookupKey(token, keys, maxDist) {
  const m = fuzzyMatch(token, keys, maxDist);
  return m ? m.candidate : null;
}
